### ISSUE TITLE
[bug] Chrome web store version 1.1.0 Github repositories value 404

### ISSUE THREAD

**Issue by cage1016** [medyo/hackertab.dev#19] opened 2021-02-26 02:56 UTC
```
Request URL: https://api.hackertab.dev/data/github/golang/daily.json
Request Method: GET
Status Code: 404 
```

__src/Constants.js___
```js
...
           value: "go",
            label: "Go",
            githubValues: ["golang"],
            confsValues: ["go"],
            stackoverflowValues: ["go"],
            devtoValues: ["go"]
        }, {
...
```

compare Chrome web store version 1.1.0. the repo master version has been fixed GitHub repository value not found issue

```
  {
    value: 'go', label: 'Go',
    githubValues: ['go'], confsValues: ['go'],
    stackoverflowValues: ['go'], devtoValues: ['go']
  },
```

Please release the new version to Chrome web store. 
Thanks. a lot (rock)

**Comment by medyo** [comment] 2021-02-26 11:06
duplicate of #15 
The changes have been deployed (waiting for chrome to approve them)

**Closed by medyo** 2021-02-26 11:06 UTC
Labels: duplicate
